/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#8ff0a8",
        "inverse-primary": "#a8c8ff",
        "surface-bright": "#f4faff",
        "on-background": "#0f1d24",
        "error": "#ba1a1a",
        "inverse-surface": "#243239",
        "tertiary": "#005429",
        "on-primary-container": "#cadcff",
        "on-primary": "#ffffff",
        "tertiary-container": "#006f38",
        "on-secondary-fixed": "#001f2a",
        "on-primary-fixed": "#001b3d",
        "primary-fixed": "#d6e3ff",
        "outline-variant": "#c2c6d4",
        "surface-container-highest": "#d5e5ee",
        "surface-container-high": "#dbebf4",
        "on-secondary-fixed-variant": "#004d65",
        "on-secondary": "#ffffff",
        "outline": "#727783",
        "tertiary-fixed": "#96f7af",
        "on-tertiary-fixed-variant": "#005228",
        "surface-container-low": "#e7f6ff",
        "primary-fixed-dim": "#a8c8ff",
        "on-tertiary": "#ffffff",
        "surface-tint": "#005db5",
        "surface-variant": "#d5e5ee",
        "background": "#f4faff",
        "on-surface-variant": "#424752",
        "inverse-on-surface": "#e3f3fd",
        "on-tertiary-fixed": "#00210c",
        "secondary-container": "#90dbff",
        "surface-container": "#e0f0fa",
        "on-primary-fixed-variant": "#00468b",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "surface": "#f4faff",
        "secondary-fixed-dim": "#84d0f4",
        "on-secondary-container": "#00617e",
        "on-surface": "#0f1d24",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "secondary-fixed": "#bee9ff",
        "surface-dim": "#cddce6",
        "tertiary-fixed-dim": "#7ada95",
        "primary": "#00488d",
        "secondary": "#006685",
        "primary-container": "#005fb8",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      spacing: {
        "gutter-loose": "1.5rem",
        "space-lg": "1rem",
        "space-sm": "0.5rem",
        "space-2xl": "2rem",
        "gutter": "1rem",
        "space-xs": "0.25rem",
        "space-xl": "1.5rem",
        "space-md": "0.75rem",
        "margin-compact": "1rem",
        "margin": "1.5rem",
      },
      fontFamily: {
        "label-md": ["Inter"],
        "headline-md": ["Inter"],
        "title-md": ["Inter"],
        "headline-lg": ["Inter"],
        "title-sm": ["Inter"],
        "display": ["Inter"],
        "code-sm": ["JetBrains Mono"],
        "body-md": ["Inter"],
        "headline-sm": ["Inter"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "body-sm": ["Inter"],
      },
      fontSize: {
        "label-md": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "500" }],
        "headline-md": ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-md": ["1rem", { lineHeight: "1.375rem", fontWeight: "600" }],
        "headline-lg": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "title-sm": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "600" }],
        "display": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "code-sm": ["0.75rem", { lineHeight: "1rem", fontWeight: "400" }],
        "body-md": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        "headline-sm": ["1.125rem", { lineHeight: "1.5rem", fontWeight: "600" }],
        "body-lg": ["1rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "label-sm": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-sm": ["0.75rem", { lineHeight: "1rem", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
